"""Events: replace device with sensor

Revision ID: 1
Revises: 0
Create Date: 2018-06-08 15:29:59.937145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1'
down_revision = '0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sensor_ids', sa.String(), nullable=True))
        batch_op.drop_column('device_ids')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_ids', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('sensor_ids')

    # ### end Alembic commands ###
