"""Database creation

Revision ID: 0
Revises: 
Create Date: 2018-03-30 17:56:19.838553

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('application', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('execution_timestamp', sa.DateTime(), nullable=True),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('building_id', sa.String(), nullable=True),
    sa.Column('floor_id', sa.String(), nullable=True),
    sa.Column('space_id', sa.String(), nullable=True),
    sa.Column('device_ids', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('reliability', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
